name: regression
on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install deps
      run: sudo apt update && sudo apt install -y curl sudo luarocks make && \
        sudo luarocks install luacheck && \
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0

    - name: Run tests
      run: make test
